from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


STATUS = ((0, "Draft"), (1, "Published"))

class Post(models.Model):
    """
    This Post class is setting up the post model for
    how it will appear on the admin panel as well as
    how it will display to the user and will
    also show what field type each field will be
    and what criteria must be met for some of them
    to be accepted.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    featured_image = CloudinaryField('image', default='placeholder')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name="post_likes", blank=True)
    
    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title}"

    def number_of_likes(self):
        return self.likes.count()  



class Comment(models.Model):
    """
    The Comment Model is showing which fields will be
    completed and displayed when a user leaves a comment
    under the post including those that are autogenerated
    and those that required compeltion by the user.
    """
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_on"]
        
    def __str__(self):
        return f"{self.body}. By {self.author}"